
/**************************************************************
 *	
 *	collide, 8 bit, 22050Hz,
 *	1 channel, 4343 bytes/channel
 *	Total Size: 1 * 4343 + 4 (header) = 4387 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Owner\Documents\NetBeansProjects\RyanDiaz_FinalProject\collide.wav
 *	Time-stamp: Fri Apr 25 07:43:00 2014
 *	
 **************************************************************/

#ifndef __COLLIDEH__
#define __COLLIDEH__

#define COLLIDEFREQ 22050
#define COLLIDELEN 4343

extern const unsigned char collide[4343];

#endif /* __COLLIDEH__ */
