
/**************************************************************
 *	
 *	defeat, 8 bit, 11025Hz,
 *	1 channel, 155703 bytes/channel
 *	Total Size: 1 * 155703 + 4 (header) = 155747 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Owner\Documents\NetBeansProjects\RyanDiaz_FinalProject\defeat.wav
 *	Time-stamp: Fri Apr 25 07:58:09 2014
 *	
 **************************************************************/

#ifndef __DEFEATH__
#define __DEFEATH__

#define DEFEATFREQ 11025
#define DEFEATLEN 155703

extern const unsigned char defeat[155703];

#endif /* __DEFEATH__ */
