
/**************************************************************
 *	
 *	gameMusic, 8 bit, 11025Hz,
 *	1 channel, 504261 bytes/channel
 *	Total Size: 1 * 504261 + 4 (header) = 504305 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Owner\Documents\NetBeansProjects\RyanDiaz_FinalProject\gameMusic.wav
 *	Time-stamp: Fri Apr 25 07:16:19 2014
 *	
 **************************************************************/

#ifndef __GAMEMUSICH__
#define __GAMEMUSICH__

#define GAMEMUSICFREQ 11025
#define GAMEMUSICLEN 504261

extern const unsigned char gameMusic[504261];

#endif /* __GAMEMUSICH__ */
