
/**************************************************************
 *	
 *	opening2, 8 bit, 11025Hz,
 *	1 channel, 2248704 bytes/channel
 *	Total Size: 1 * 2248704 + 4 (header) = 2248748 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Owner\Documents\NetBeansProjects\RyanDiaz_FinalProject\opening2.wav
 *	Time-stamp: Fri Apr 25 06:55:22 2014
 *	
 **************************************************************/

#ifndef __OPENING2H__
#define __OPENING2H__

#define OPENING2FREQ 11025
#define OPENING2LEN 2248704

extern const unsigned char opening2[2248704];

#endif /* __OPENING2H__ */
