
/**************************************************************
 *	
 *	victory, 8 bit, 11025Hz,
 *	1 channel, 173782 bytes/channel
 *	Total Size: 1 * 173782 + 4 (header) = 173826 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Owner\Documents\NetBeansProjects\RyanDiaz_FinalProject\victory.wav
 *	Time-stamp: Fri Apr 25 07:51:13 2014
 *	
 **************************************************************/

#ifndef __VICTORYH__
#define __VICTORYH__

#define VICTORYFREQ 11025
#define VICTORYLEN 173782

extern const unsigned char victory[173782];

#endif /* __VICTORYH__ */
