
/**************************************************************
 *	
 *	walk, 8 bit, 44100Hz,
 *	1 channel, 4912 bytes/channel
 *	Total Size: 1 * 4912 + 4 (header) = 4956 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Owner\Documents\NetBeansProjects\RyanDiaz_FinalProject\walk.wav
 *	Time-stamp: Fri Apr 25 06:12:15 2014
 *	
 **************************************************************/

#ifndef __WALKH__
#define __WALKH__

#define WALKFREQ 44100
#define WALKLEN 4912

extern const unsigned char walk[4912];

#endif /* __WALKH__ */
